### ISSUE TITLE
type "tinytext" does not exist

### ISSUE THREAD

**Issue by sagarey** [EnterpriseDB/mysql_fdw#151]
When I create foreign table use IMPORT FOREIGN SCHEMA cause this error, I have to use CAST to convert group_concat result type in view definition.

**Comment by slava-pagerduty** [comment]
you can easily fix it yourself, see https://github.com/EnterpriseDB/mysql_fdw/issues/154
hopefully someone from EnterpriseDB will update datatypes mapping in `mysqlImportForeignSchema()`

**Comment by cbandy** [comment]
Fixed by https://github.com/EnterpriseDB/mysql_fdw/commit/d04b0c8a6dcf2a025f3c6f0a471f637a79781a02 perhaps?

**Comment by slava-pagerduty** [comment]
why the similar issue around binary/varbinary types that I have reported was not fixed?
https://github.com/EnterpriseDB/mysql_fdw/issues/154
