### ISSUE TITLE
Sending additional connection parameters

### ISSUE THREAD

**Issue by benmadin** [EnterpriseDB/mysql_fdw#39]
G'day,

this might be the wrong location, but we have used the mysql fdw to help migrate off a number of old (but production) mysql servers... so thank you.

Our problem is now an upgrade of a 'very' legacy system. The only way we can connect is by setting ```secure-auth``` to ```'disabled'```, i.e. by including the ```--skip-secure-auth``` flag.

Is it possible to somehow include that in the options for the connection? Or do I need to learn C?

cheers

Ben

**Comment by ibrarahmad** [comment]
I am middle of doing another task, I will add that option next week.

On Wed, Feb 11, 2015 at 6:04 PM, benmadin <notifications@github.com> wrote:

> G'day,
>
> this might be the wrong location, but we have used the mysql fdw to help
> migrate off a number of old (but production) mysql servers... so thank you.
>
> Our problem is now an upgrade of a 'very' legacy system. The only way we
> can connect is by setting secure-auth to 'disabled', i.e. by including
> the --skip-secure-auth flag.
>
> Is it possible to somehow include that in the options for the connection?
> Or do I need to learn C?
>
> cheers
>
> Ben
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/39>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by benmadin** [comment]
Super - thank you!

**Comment by ibrarahmad** [comment]
I have added a support to enable / disable secure authentication in server options

option (secure_auth 'false'). 

Can you please test that, because I don't have any legacy system to test that.

**Comment by ahsanhadi** [comment]
On Thu, Feb 26, 2015 at 12:11 AM, Ibrar Ahmed <notifications@github.com>
wrote:

> I have added a support to enable / disable secure authentication in server
> options
>
> option (secure_auth 'false').
>

This is true by default...


>  Can you please test that, because I don't have any legacy system to test
> that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/39#issuecomment-76033153>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by benmadin** [comment]
Hello,

my apologies for the long delay in responding. I have tested this, and it appears to work OK on a local system, insofar as if I specify OPTIONS (secure_auth 'false') in my connection, I get

    # SELECT * FROM mysql.users_local;
    WARNING:  MySQL secure authentication is off
     userid |         username          |     password     |         firstname         |      surname      |  title   |                           position              

etc.

but if I connect to the remote (very old server) with the same connection string, I get :

    # SELECT * FROM mysql.users_live;
    WARNING:  MySQL secure authentication is off
    ERROR:  failed to prepare the MySQL query: 
    Unknown command

I don't know how best I can help here, or why it is failing to prepare the query?

cheers

Ben

**Comment by ibrarahmad** [comment]
On Tue, Apr 7, 2015 at 8:50 PM, benmadin <notifications@github.com> wrote:

> Hello,
>
> my apologies for the long delay in responding. I have tested this, and it
> appears to work OK on a local system, insofar as if I specify OPTIONS
> (secure_auth 'false') in my connection, I get
>
> # SELECT * FROM mysql.users_local;
> WARNING:  MySQL secure authentication is off
>  userid |         username          |     password     |         firstname         |      surname      |  title   |                           position
>
> etc.
>
> but if I connect to the remote (very old server) with the same connection
> string, I get :
>

Can you please tell me the version of old server, is this still available
for download?



> # SELECT * FROM mysql.users_live;
> WARNING:  MySQL secure authentication is off
> ERROR:  failed to prepare the MySQL query:
> Unknown command
>
> I don't know how best I can help here, or why it is failing to prepare the
> query?
>
> cheers
>
> Ben
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/39#issuecomment-90617125>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by benmadin** [comment]
Hi Ahmed,

our server is : Server version: 3.23.56

it does look like it is still available (
http://olex.openlogic.com/packages/mysql/3.23.58)

I appreciate your help, but please don't spend too long on this if we are
the only people every likely to need this function!

cheers

Ben




On 8 April 2015 at 16:01, Ibrar Ahmed <notifications@github.com> wrote:

> On Tue, Apr 7, 2015 at 8:50 PM, benmadin <notifications@github.com> wrote:
>
> > Hello,
> >
> > my apologies for the long delay in responding. I have tested this, and it
> > appears to work OK on a local system, insofar as if I specify OPTIONS
> > (secure_auth 'false') in my connection, I get
> >
> > # SELECT * FROM mysql.users_local;
> > WARNING: MySQL secure authentication is off
> > userid | username | password | firstname | surname | title | position
> >
> > etc.
> >
> > but if I connect to the remote (very old server) with the same connection
> > string, I get :
> >
>
> Can you please tell me the version of old server, is this still available
> for download?
>
>
>
> > # SELECT * FROM mysql.users_live;
> > WARNING: MySQL secure authentication is off
> > ERROR: failed to prepare the MySQL query:
> > Unknown command
> >
> > I don't know how best I can help here, or why it is failing to prepare
> the
> > query?
> >
> > cheers
> >
> > Ben
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EnterpriseDB/mysql_fdw/issues/39#issuecomment-90617125>
> > .
> >
>
>
>
> --
> Ibrar Ahmed
> EnterpriseDB http://www.enterprisedb.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/39#issuecomment-90835915>
> .
>



-- 

Ben Madin
BVMS PhD, MANZCVS

t : +61 8 6102 5535
m : +61 448 887 220
e : ben@ausvet.com.au

AusVet Animal Health Services
Western Australia

www.ausvet.com.au

**Comment by ahsanhadi** [comment]
Can you please close this case as the initial issue of not being able to connect to the old server is addressed by adding the required clause to the connection option. If needed you can raise another query for not being able to execute a query on a old remote server...

**Comment by benmadin** [comment]
Hi,

in fact, adding the clause only works on a new server version, but we still cannot connect to an older server. So I'm not sure if it is resolved yet. However, I'll leave it to Ahmed to decide!

thank you 

cheers

Ben
